spring:
  application:
    name: chatflow-server
  r2dbc:
    url: r2dbc:mysql://localhost:3306/chatflow?sslMode=DISABLED&allowPublicKeyRetrieval=true
    username: chatflow
    password: chatflow
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: chatflow-server
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.chatflow.kafka.dto
        spring.json.value.default.type: com.chatflow.kafka.dto.ChatMessageSentEvent
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/chatflow?sslMode=DISABLED&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
    user: chatflow
    password: chatflow
    locations: classpath:db/migration

server:
  port: 8081

chatflow:
  jwt:
    secret: "dev-only-change-me-please-use-at-least-32-bytes-for-hmac-sha256-keys"
    expiration-ms: 86400000

logging:
  level:
    com.chatflow: INFO
    org.springframework.r2dbc: DEBUG
